### ISSUE TITLE
something in the dBiz modules crashes Rack

### ISSUE THREAD

**Issue by davephillips** [dBiz/VCVRack_Modules#5]
Linux Fedora 23
VCV Rack dev (13 November 2017)

When I move the mouse cursor into the dBiz menu it crashes Rack. Here's the segfault and backtrace from 'make debug', please advise if you need more information. 

Program received signal SIGSEGV, Segmentation fault.
0x000000000047f390 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider (__a=..., __dat=<optimized out>, 
    this=<optimized out>) at /usr/include/c++/5.3.1/bits/basic_string.h:109
109		: allocator_type(__a), _M_p(__dat) { }

#0  0x000000000047f390 in rack::MetadataMenu::step() (__a=..., __dat=<optimized out>, this=<optimized out>) at /usr/include/c++/5.3.1/bits/basic_string.h:109
#1  0x000000000047f390 in rack::MetadataMenu::step() (__str=..., this=0x7fffffffd690) at /usr/include/c++/5.3.1/bits/basic_string.h:399
#2  0x000000000047f390 in rack::MetadataMenu::step() (this=0xf92b90) at src/app/AddModuleWindow.cpp:57
#3  0x0000000000474ded in rack::Widget::step() (this=0xf911d0) at src/widgets/Widget.cpp:105
#4  0x0000000000474ded in rack::Widget::step() (this=0xf92c18) at src/widgets/Widget.cpp:105
#5  0x0000000000474ded in rack::Widget::step() (this=0xf90da0) at src/widgets/Widget.cpp:105
#6  0x0000000000474ded in rack::Widget::step() (this=0x106a4c8) at src/widgets/Widget.cpp:105
#7  0x0000000000470281 in rack::MenuOverlay::step() (this=0x106a4c0) at src/widgets/MenuOverlay.cpp:8
#8  0x0000000000474ded in rack::Widget::step() (this=0xb8ce50) at src/widgets/Widget.cpp:105
#9  0x000000000047767b in rack::RackScene::step() (this=0xb8ce30) at src/app/RackScene.cpp:65
#10 0x00000000004489e6 in rack::guiRun() () at src/gui.cpp:428
#11 0x000000000043266c in main(int, char**) (argc=1, argv=0x7fffffffda78) at src/main.cpp:39

**Comment by davephillips** [comment]
Okay, I retrieved fresh sources from git and rebuilt, deleting everything from the build except the VCA, the DVCO, and the VerboOsc, those are the modules I'm most interested in. After a clean build the problem appears to have vanished, at least with only those three modules built into plugin.so.

I also edited the Makefile to be more like the one for the Fundamental plugins. It appears that the original Makefile had been copied from the Audible Instruments sources, it was bringing in stuff that wasn't used or needed, AFAICT.

Cool stuff, thanks for making these modules. :)
